import { AboutSection, ContactForm, ContactInfo, MainSection, ManagementTeam, Partners } from "@/futures"
import { Flex } from "@mantine/core"
import { useMediaQuery } from "@mantine/hooks"
import cx from "clsx"
import Head from "next/head"

import s from "./styles.module.scss"

const HomePage = () => {
	const matches = useMediaQuery("(max-width: 992px)")

	return (
		<>
			<Head>
				<title>SOGDA UNITED TRADE</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<MainSection />
				<AboutSection />
				<Partners />
				<ManagementTeam />
				<Flex
					id={"section3"}
					pt={matches ? 32 : 120}
					className={"container"}
					gap={22}
					align={"stretch"}
					direction={matches ? "column" : "row"}
				>
					<ContactInfo />
					<ContactForm />
				</Flex>

				<div id={"section4"} className={cx(s.map, "container")}>
					<iframe
						src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2996.1959622354984!2d69.31764151202475!3d41.326351971188046!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8b5db61c9d6b%3A0x2a8697df753f4f1b!2z0J7QntCeIMKrU21hcnQgU29mdCBEZXZlbG9wbWVudMK7!5e0!3m2!1sru!2s!4v1728418098491!5m2!1sru!2s"
						style={{ border: 0 }}
						allowFullScreen
						loading={"lazy"}
						referrerPolicy={"no-referrer-when-downgrade"}
					/>
				</div>
			</main>
		</>
	)
}

export default HomePage
