import {
	AboutSection,
	ContactForm,
	ContactInfo,
	MainSection,
	ManagementTeam,
	Partners,
} from "@/futures"
import { Flex } from "@mantine/core"
import { useMediaQuery } from "@mantine/hooks"
import cx from "clsx"
import Head from "next/head"

import s from "./styles.module.scss"

const HomePage = () => {
	const matches = useMediaQuery("(max-width: 992px)")

	return (
		<>
			<Head>
				<title>SOGDA UNITED TRADE</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<MainSection />
				<AboutSection />
				<Partners />
				<ManagementTeam />
				<Flex
					id={"section3"}
					pt={matches ? 32 : 120}
					className={"container"}
					gap={22}
					align={"stretch"}
					direction={matches ? "column" : "row"}
				>
					<ContactInfo />
					<ContactForm />
				</Flex>

				<div id={"section4"} className={cx(s.map, "container")}>
					<iframe
						src="https://yandex.ru/map-widget/v1/?um=constructor%3A4299f47342194d25a47eaca19c02e6ee37349296ae11f81d2af71a35dc17b34c&amp;source=constructor"
						width="100%"
						height="400"
						frameBorder="0"
					></iframe>
				</div>
			</main>
		</>
	)
}

export default HomePage
