import {
	AboutSection,
	ContactForm,
	ContactInfo,
	MainSection,
	ManagementTeam,
	Partners,
} from "@/futures"
import { Flex } from "@mantine/core"
import { useMediaQuery } from "@mantine/hooks"
import cx from "clsx"
import Head from "next/head"
import React from "react"

import { Navbar } from "@/widgets/layout/navbar"


import s from "./styles.module.scss"
import { Footer } from "@/widgets/layout/footer"

const HomePage = () => {
	const matches = useMediaQuery("(max-width: 992px)")

	return (
		<>
			<Head>
				<title>SOGDA UNITED TRADE</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar
					menuItems={[
						{ label: "О нас", section: 1 },
						{ label: "Команда", section: 2 },
						{ label: "Контакты", section: 3 },
						{
							label: "Мы на карте",
							section: 4,
						},
					]}
				/>
				<MainSection />
				<AboutSection />
				<Partners />
				<ManagementTeam />
				<Flex
					id={"section3"}
					pt={matches ? 32 : 120}
					className={"container"}
					gap={22}
					align={"stretch"}
					direction={matches ? "column" : "row"}
				>
					<ContactInfo
						title="Контакты"
						sectionLabel="Свяжитесь с нами"
						addressLabel={"Адрес:"}
						address="Республика Узбекистан, г. Самарканд, ул. М. Хайдарова 29"
						phoneLabel={"Телефон:"}
						phone="+998981706000"
						emailLabel={"Почта:"}
						email="info@sogda-united.uz"
						phoneCall={"Позвонить в компанию"}
						emailWrite={"Написать на почту"}
					/>
					<ContactForm
						sectionLabel={'Или оставьте свой номер'}
						title={'Оставить заявку'}
						name={'Имя:'}
						namePlaceholder={'Виктор'}
						phone={'Телефон:'}
						phonePlaceholder={'Телефон'}
						emailInput={'Почта:'}
						emailPlaceholder={'mail@yandex.ru'}
						button={'Позвонить в компанию'}
					/>
				</Flex>

				<div id={"section4"} className={cx(s.map, "container")}>
					<iframe
						src="https://yandex.ru/map-widget/v1/?um=constructor%3A4299f47342194d25a47eaca19c02e6ee37349296ae11f81d2af71a35dc17b34c&amp;source=constructor"
						width="100%"
						height="400"
						frameBorder="0"
					></iframe>
				</div>
			</main>
			<Footer/>
		</>
	)
}

export default HomePage
